---

# This is made as a playbook, not as a list of task to include with 'include_tasks'
# module only because of 'ms_comment_multiline_string' custom filter plugin usage.
# https://docs.ansible.com/ansible/latest/plugins/filter.html#enabling-filter-plugins

- name: Update script settings
  hosts: "{{ ansible_limit | default(omit) }}"
  gather_facts: false
  module_defaults:
    group/community.routeros.api:
      hostname: "{{ mikrotik_host_name | default(inventory_hostname) }}"
      password: "{{ mikrotik_api_password }}"
      username: "{{ ansible_user }}"
      tls: "{{ mikrotik_use_tls | default(true) }}"
      validate_certs: "{{ mikrotik_use_tls | default(true) }}"
      validate_cert_hostname: "{{ mikrotik_use_tls | default(true) }}"
  tasks:

    - name: Check that mandatory variables are defined
      ansible.builtin.assert:
        that:
          - ms_install_script_name is defined
        quiet: true

    - name: Include script installation settings
      ansible.builtin.include_vars:
        file: "{{ playbook_dir }}/../../{{ ms_install_script_name }}/install.yml"

    - name: Generate settings script content
      ansible.builtin.include_tasks:
        file: generate_script_settings.yml
      vars:
        ms_actual_script_settings: "{{ lookup('vars', 'ms_' + ms_install_script_name + '_script_settings') }}"

    - name: Add comment to settings script
      ansible.builtin.set_fact:
        _ms_settings_script_content: |
          # Generated by Ansible. Any changes made here will be overwritten.
          # https://github.com/cheretbe/mikrotik-scripts/blob/master/{{ ms_install_script_name }}/README.md

          {{ _ms_settings_script_content }}

    - name: Install settings script
      ansible.builtin.include_tasks:
        file: download_and_install_script_item.yml
      vars:
        _ms_install_script:
          content: "{{ _ms_settings_script_content }}"
          name: "{{ ms_install_script_name }}_settings"
          overwrite: true
