
Vagrant.configure("2") do |config|
  config.vm.define :isp1 do |isp1|
    isp1.vm.box = "ubuntu/xenial64"
    isp1.vm.hostname = "isp1"
    isp1.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    isp1.vm.network "private_network", ip: "192.168.120.10", virtualbox__intnet: "vagrant-isp1"

    isp1.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "isp_provision.yml"
      ansible.compatibility_mode = "2.0"
      ansible.become = true
      ansible.extra_vars = {
        nat_source: "192.168.120.0/24"
      }
    end
  end

  config.vm.define :isp2 do |isp2|
    isp2.vm.box = "ubuntu/xenial64"
    isp2.vm.hostname = "isp2"
    isp2.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
      vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    end
    isp2.vm.network "private_network", ip: "192.168.121.10", virtualbox__intnet: "vagrant-isp2"

    isp2.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "isp_provision.yml"
      ansible.compatibility_mode = "2.0"
      ansible.become = true
      ansible.extra_vars = {
        nat_source: "192.168.121.0/24"
      }
    end
  end

  config.vm.define :"router" do |router|
    router.vm.box = "cheretbe/routeros"
    router.vm.provider "virtualbox" do |vb|
      vb.customize ["modifyvm", :id, "--groups", "/__vagrant"]
    end
    router.vm.network "private_network", virtualbox__intnet: "vagrant-lan", auto_config: false
    router.vm.network "private_network", virtualbox__intnet: "vagrant-isp1", auto_config: false
    router.vm.network "private_network", virtualbox__intnet: "vagrant-isp2", auto_config: false

    router.vm.provision "routeros_file", name: "Upload provision script",
      source: "router_provision.rsc", destination: "router_provision.rsc"

    router.vm.provision "routeros_command", name: "Run provision script",
      command: "/import router_provision.rsc"
  end
end